### ISSUE TITLE
New Questions

### ISSUE THREAD

**Issue by dalyw01** [mwall01/weekly-wall#7]
I'd love some new questions from @tkavlearning

Thoughts?

**Comment by tkavlearning** [comment]
Oh I think I can rustle up a few more! Cheers for the tag in @dalyw01 !!

Will make sure to pull down the most recent version and see whats there first!

**Comment by dalyw01** [comment]
Thank you for the quick response @tkavlearning , appreciate you taking the time to look into my issue.

Regards,

Will

**Comment by tkavlearning** [comment]
No problem at all @dalyw01 !!
I just have to finish some notetaking tasks and will jump in!

Have a lovely, lovely day!

**Comment by tkavlearning** [comment]
hey @dalyw01 !! Thanks so much for your patience while I worked on this for you!

You can find some new questions added https://github.com/mwall01/weekly-wall/pull/8 . Feel free to review!

If anything else pops up please let me know and I would be more than happy to take a look at it for you!

Cheers!

**Comment by dalyw01** [comment]
Thanks @tkavlearning 

Provided feedback. Waiting on @tweigelt-sqsp to review.

Regards,

Will

**Comment by tkavlearning** [comment]
Hey there @dalyw01!

Just an update to let you know #8 was closed to deal with a pesky pesky merge conflict

#9 is hot off the press if you'd like to take a look! 

Thanks again for being a loyal customer!
